### ISSUE TITLE
Missing support for x86_64 + missing source code

### ISSUE THREAD

**Issue by julianxhokaxhiu** [sdomotica/hassio-addons#14]
Hello,

I'd be interested in running one of your images, however the fact that is not open source and is limited only to ARM is quite limiting. Is there any particular reason why there's yet no x86_64 option available, and especially why there's no source code for any of the docker images you publish?

Thank you in advance and best regards,
Julian

**Comment by sdomotica** [comment]
I have some non ARM test addon. But every hardware respond  in different way.
For e.g. on Synology NAS the addon create a lot of waste volumes that spam the disk end make it full very quicly.

Other aspect , just because my is a paid solution I have to guaranty the functionality.
And for me will be too much honerous follow all the platfroms
The HA guys are continuing changing the system. Recently I documented a big issue for my adons and don't have any answer.

Look here
https://github.com/home-assistant/supervisor/issues/5493#issuecomment-2548745548

I well documented and indicated the issue in the logs.

No answer...

If you would use my addon , you can use a bridge approach

https://www.dropbox.com/scl/fi/wwar70uipbsbcdnv0kuy6/Hassio_Sdomotica_Bridge-2023.pdf?rlkey=ycttyubet28bg5nyqm0a4ufj4&dl=0

Bye
Sandro

**Comment by julianxhokaxhiu** [comment]
Thanks a lot for the reply.

> Other aspect , just because my is a paid solution I have to guaranty the functionality.

I wasn't aware this product comes in paid form, I found the repo and I thought it was open source so I was wondering where I could find the source code. Thanks for clarifying that.

> The HA guys are continuing changing the system. Recently I documented a big issue for my adons and don't have any answer.

I wasn't aware of this as well of this bug, is that what is blocking you for releasing it for x86_64?

> If you would use my addon , you can use a bridge approach

I'll have a look into this, thank you.

Wish you a happy new year and best regards,
Julian

**Comment by sdomotica** [comment]
There is already a opensource and cross platform solution

https://community.home-assistant.io/t/legrand-bticino-myhome/229337?u=sdomotica_automation

The difference from mine and this is that I'm here for help the user, but as you can note the author of free don't answer anymore to users.

Happy new year too.
Bye
Sandro

**Comment by julianxhokaxhiu** [comment]
> There is already a opensource and cross platform solution

Is that valid as well for the ksenia40 one? I was looking specifically for that code. Thanks for the link by the way, really appreciated :)

**Comment by sdomotica** [comment]
Ksenia require to sing a NDA for release the API. Thus isn't possibile share the open code. I don't know open source project.
